### ISSUE TITLE
Location text exceeds available space

### ISSUE THREAD

**Issue by equinoxmatt** [Theldus/windy#1]
First off, I love what you're doing here. It's refreshing to see lightweight applications that don't rely on an entire browser engine, and kudos for using C.

I've noticed a minor issue, though I'm not entirely sure about the best remedy. If the location name is too long, the text can spill out of the window. Here's an example:

![image](https://github.com/Theldus/windy/assets/5101742/3e052292-bcaf-48b8-b209-0aea2d86b54b)

I can think of a couple of potential solutions:

1. Dynamically adjust the window size based on the length of the location name, ensuring everything fits.
2. Use an ellipsis when the location name exceeds the available width.

I'd be interested in your thoughts on this!

**Comment by Theldus** [comment]
Hi @equinoxmatt,
Thanks for the compliments, choosing C was pretty natural for me as I definitely don't do anything web =), and using SDL there is great portability too =).

About the issue, resizing the window, as suggested in 1), would be kind of troublesome, since the assets are fixed-size and etc, so the solution in 2) would really be the way to go, for me.

I'll work on it and let you know when I'm done, thanks for reporting this =).

**Comment by Theldus** [comment]
Hi @equinoxmatt,
Commit 1512331 should fix this, both for the location text and the provider (which could also exceed the window size):

![int](https://github.com/Theldus/windy/assets/8294550/7f850b9b-c75b-42ab-a3d6-25cd62754498)

In your case, though, it might be better to use as 'location': "Thornton-Cleveleys, UK", to avoid truncating.

Please let me know if there are any remaining questions, and if this fix works for you.
Again, thanks for reporting this and testing Windy =).

**Comment by equinoxmatt** [comment]
Fantastic, thank you for the quick fix.
