### ISSUE TITLE
Cannot build on archlinux

### ISSUE THREAD

**Issue by DaarkWel** [Theldus/windy#2]
A lot of errors. Maybe because of changes in latest SDL3? SDL3 and SDL3_ttf are installed.
[build.log](https://github.com/user-attachments/files/18135340/build.log)

**Comment by Theldus** [comment]
Hi @DaarkWel,
Thanks for giving Windy a try!

You're completely right! As SDL3 is still under development, a lot of the API have changed since I've used it, which explains your build issues. Thanks for reporting this.

Commit 0d4678fa956ea94ecbff2c0f4b143b3b574d10c8 updates Windy to the most recent commit for SDL3 and SDL3_ttf (hashes 6cc9ce183 and 0ad0c2518), and should address all the build issues.

Please let me know if this works for you.

**Comment by DaarkWel** [comment]
Thanks, now it builds but doesn't run. I'll open another issue.

Nope, sorry, it runs ok. My bad. Cheers.
